// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Positions.ConsoleApp.Data;

#nullable disable

namespace Positions.ConsoleApp.Migrations
{
    [DbContext(typeof(PositionsDbContext))]
    [Migration("20250826145430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Positions.ConsoleApp.Models.PositionEntity", b =>
                {
                    b.Property<string>("PositionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(38,18)")
                        .HasColumnName("value");

                    b.HasKey("PositionId", "Date");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_positions_client");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_positions_date");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_positions_product");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_positions_value");

                    b.ToTable("tb_positions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
